### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by JohnCoene** [JohnCoene/ambiorix#21]
Add tests.

Need input/ideas on how to do this best for web servers, .e.g.: mock requests, etc.

**Comment by vikram-rawat** [comment]
I couldn't find CORS in documents... Just wanted to know if it has been implemented yet.

**Comment by JohnCoene** [comment]
CORS is just about custom headers to the best of my understanding, this can be done with Ambiorix. Could you elaborate?

**Comment by vikram-rawat** [comment]
if I just create an API. I would need an authentication mechanism and a Cross origin reference to let some server talk to it... An API running on port 3000 can not be accessed by a webpage served on 4000... This is how I understand CORS... Most of the framework allow you to provide a set of links from where the API can be called...

**Comment by JohnCoene** [comment]
An API running on port 3000 can be accessed by another on port 4000 by default. To the best of understanding, CORS works the other way around it's to restrict access.

This takes the form of [headers](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) which can be handled here too, it would take the form of a middleware that adds said headers to all requests.
