### ISSUE TITLE
Side by side comparaison with Shiny in examples

### ISSUE THREAD

**Issue by DivadNojnarg** [JohnCoene/ambiorix#31]
Will help user doing the transition

**Comment by JohnCoene** [comment]
I added an example [here](https://ambiorix.john-coene.com/#/examples/shiny) (many more to come).

_It's difficult to put side by side since ambiorix projects generally consist of multiple files_

**Comment by DivadNojnarg** [comment]
The example is useful! I'll encourage you to treat use case like:
- updating input
-

**Comment by JohnCoene** [comment]
Let me know if any other good examples come to mind, I'm a taker!
